try fix: Failure/Error require File. Push credentials.yml.enc.
error
---
Failure/Error: require File.expand_path('../../config/environment', __FILE__)

NoMethodError:
undefined method `[]' for nil:NilClass
---