try fix: Failure/Error require File. Set RAIL_MASTER_KEY value to CircleCI Settings.
error
---
Failure/Error: require File.expand_path('../../config/environment', __FILE__)

NoMethodError:
undefined method `[]' for nil:NilClass
---