fix: Failure/Error require File
error
---
An error occurred while loading ./spec/controllers/comments_controller_spec.rb.
Failure/Error: require File.expand_path('../../config/environment', __FILE__)

NoMethodError:
  undefined method `[]' for nil:NilClass
---